### ISSUE TITLE
BLE device scan can't find any device

### ISSUE THREAD

**Issue by bdevay** [wolfc01/flutter_reactive_ble_uart_example#2]
Hi,

I'm using an Android physical device to run this example, and I'm using an iPhone to simulate a BLE server (nRF Connect app).
My PC (Win10) can discover and pair the simulated server is running on iOS, but this example can't discover any surrounding device.

Of course, I gave access to Bluetooth when I started the app. If I turn off the Bluetooth on Android, then the status message shows the error properly.

I have no clue what's wrong. Can you give me a hint?

**Comment by wolfc01** [comment]
Hi,

Sorry for late responding. 

This app only react to specific Nordic UART Service (NUS) UUID.

If that is not the cause then  I suggest you have to direct your question to the creator of the ble library at https://github.com/PhilipsHue/flutter_reactive_ble. They are very responsive on reported issues.

Br
Carl
